openapi: 3.0.0
info:
  title: Claims System API
  description: API for managing claims in a Claims System
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

paths:
  /claims:
    get:
      summary: Get all claims
      operationId: getClaims
      responses:
        "200":
          description: A list of claims
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "https://raw.githubusercontent.com/ewalterwbmi/specs/main/Claim.yaml#/components/schemas/Claim"
    post:
      summary: Create a new claim
      operationId: createClaim
      requestBody:
        description: The claim to create
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/ewalterwbmi/specs/main/Claim.yaml#/components/schemas/Claim"
      responses:
        "201":
          description: The created claim
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/ewalterwbmi/specs/main/Claim.yaml#/components/schemas/Claim"

  /claims/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The ID of the claim
        schema:
          type: integer
    get:
      summary: Get a claim by ID
      operationId: getClaimById
      responses:
        "200":
          description: The claim with the specified ID
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/ewalterwbmi/specs/main/Claim.yaml#/components/schemas/Claim"
        "404":
          description: Claim not found
    put:
      summary: Update a claim by ID
      operationId: updateClaimById
      requestBody:
        description: The updated claim
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/ewalterwbmi/specs/main/Claim.yaml#/components/schemas/Claim"
      responses:
        "200":
          description: The updated claim
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/ewalterwbmi/specs/main/Claim.yaml#/components/schemas/Claim"
        "404":
          description: Claim not found
    delete:
      summary: Delete a claim by ID
      operationId: deleteClaimById
      responses:
        "204":
          description: Claim deleted
        "404":
          description: Claim not found
